apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - image: mariadb
        name: mariadb
        env:
          # Use secret in real usage
        - name: MARIADB_ROOT_PASSWORD 
          value: ThisIsATerriblePassword
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: mariadb-persistent-storage
          mountPath: /var/lib/mysql
        - name: auditlog
          mountPath: /var/log/mysql
      - name: mariadb-audit
        image: busybox
        args:
         - /bin/sh
         - -c
         - tail -Fn+1 /var/log/mysql/server_audit.log
        volumeMounts:
        - name: auditlog
          mountPath: /var/log/mysql
      volumes:
      - name: mariadb-persistent-storage
        persistentVolumeClaim:
          claimName: mariadb-pv-claim
      - name: auditlog
        emptyDir: {}
