{
 "title": "MySQL Auditing",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Connections Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count by(username, host) (rate({container=\"mariadb-audit\"} | pattern `<timestamp>,<serverhost>,<username>,<host>,<connectionid>,<queryid>,<operation>,<database>,'<query>'<object>,<retcode>` | operation = `CONNECT` | username != `` [5m]))"
    }
   ]
  },
  {
   "title": "Connection Audit",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{container=\"mariadb-audit\"} | pattern `<timestamp>,<serverhost>,<username>,<host>,<connectionid>,<queryid>,<operation>,<database>,'<query>'<object>,<retcode>` | query = `` | username != ``"
    }
   ]
  },
  {
   "title": "Queries",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(username, sqlop) (rate({container=\"mariadb-audit\"} | pattern `<logtimestamp> <logcmd> <letter> <timestamp>,<serverhost>,<username>,<host>,<connectionid>,<queryid>,<operation>,<database>,'<query>'<object>,<retcode>` | line_format `{{.query}}` | regexp `(?P<sqlop>^([A-Za-z])*)` | operation  =~ `QUERY|WRITE` | line_format `{{.username}} {{.sqlop}}` [5m]))"
    }
   ]
  },
  {
   "title": "Audit Events",
   "type": "logs",
   "gridPos": { "h": 11, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "expr": "{container=\"mariadb-audit\"} | pattern `<logtimestamp> <logcmd> <letter> <timestamp>,<serverhost>,<username>,<host>,<connectionid>,<queryid>,<operation>,<database>,'<query>'<object>,<retcode>` | line_format `{{.query}}` | regexp `(?P<sqlop>^([A-Za-z])*)` | line_format `timestamp={{.timestamp}} serverhost={{.serverhost}} username={{.username}} host={{.host}} connectionid={{.connectionid}} queryid={{.queryid}} operation={{.operation}} database={{.database}} query=\"{{.query}}\" object={{.object}} returncode={{.retcode}}`"
    }
   ]
  }
 ]
}